name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Build and start services using Docker Compose
      - name: Build and Run with Docker Compose
        run: make build

      # Run tests in the Docker container
      - name: Run tests inside Docker container
        run: |
          docker-compose exec goatdb make test

      # Shut down the Docker Compose services
      - name: Tear down Docker Compose
        run: docker-compose down
